### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by vishwas-trivedi** [jenfi-eng/sshd-docker#2]
Hi,
I've tried to build a docker image using your script but I am getting the following error:

```
The authenticity of host '[localhost]:2222 ([::1]:2222)' can't be established.
RSA key fingerprint is SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:2222' (RSA) to the list of known hosts.
```

Can't connect to the container in local environment.

**Comment by nitsujri** [comment]
@vishwas-trivedi sorry about the late reply. The authenticity of host error is expected. It is not an error in the truest sense. It's because this is the [first time you've 'seen' the machine](https://superuser.com/questions/1295569/does-the-authenticity-of-host-cant-be-established-message-in-ssh-reflect-a-se). If you run the command again, it'll disappear after you've typed `yes`

If you're having connection issues, you should do an `ssh -vv -p 2222 root@localhost` and print what errors you get from there.

Most likely it's due to your private-key not being accepted.

**Comment by nitsujri** [comment]
Closed due to inactivity.
